#!/usr/bin/env bash

set -e
# set -x

machine_name='default'

# Get last directory of pwd
base=$(basename `pwd`)
base=${base/-/}

echo 'Defining basic settings ...'

# Gets container id
container_id=$(docker ps -a | awk '{ print $1,$2 }' | grep "$base" | awk '{ print $1 }')

running=$(docker inspect --format='{{.State.Running}}' "$container_id")
if [ $running == 'false' ]; then
    echo 'Your server is not running. Please use docker/start to initialize it.'
    exit 0
fi


# Sets environment
eval $(docker-machine env $machine_name)

# Gets machine ip
echo 'Getting your machine ip ...'
machine_ip=$(docker-machine ip)

# Gets port
port=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' "$container_id")

# Open browser
echo 'Opening your browser ...'
open http://"$machine_ip":"$port"

# Still need to check support of open in other distros
# Check: xdg-open