#!/usr/bin/env bash

set -e
#set -x

port=8080
path='.\/'
rebuild=false

show_help () {
    echo 'Usage: docker/start [OPTIONS] '
    echo
    echo 'Options:'
    echo '  -P            Port to be used on your server. (default: 8080)'
    echo '  -p            Path to be used as root on your server. (default: ./)'
    echo '  -f            Force rebuild on the images.'
}

parse_options() {
    set -- "$@"
    while [ "$#" -gt 0 ]; do
      case "$1" in
        -h)
            show_help
            exit 0
        ;;
        -P) port="$2"
            shift 2
        ;;
        -p) path="$2"
            path=${path/\//\\\/} # only replace first occurrence
            shift 2
        ;;
        -f) rebuild=true;
            shift 1
        ;;
        ?*) echo 'ERROR: Unknown option.'
            show_help
            exit 0
        ;;
      esac
    done
}

generate_compose_file() {
    echo 'Generating your docker-compose.yml file ...'
    sed -e s/PORT/"$port"/ -e s/PATH/"$path"/ docker/template.yml > docker-compose.yml
}

build_server() {
    # Builds and starts containers
    echo 'Building your containers ...'
    docker-compose up -d

    if [ "$rebuild" = true ]; then
        echo 'Rebuilding your images ...'
        docker-compose build --pull
    fi

    echo
    echo 'Your docker environment is up and running!' # verify if that's true
    echo 'Use docker/open-browser to access your machine.'
}

parse_options "$@"
generate_compose_file
build_server