version: '2'
services:
  nginx:
    build: ./docker/nginx/
    links:
      - php
    ports:
      - PORT:80
    volumes_from:
      - app

  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes_from:
      - app

  app:
    command: "true"
    image: php:5.6-fpm
    volumes:
      - PATH:/var/www/html