nginx:
  build: ./nginx/
  links:
    - php
  ports:
    - PORT:80
  volumes_from:
    - app

php:
  expose:
    - 9000
  image: php:7.0-fpm
  volumes_from:
    - app

app:
  command: "true"
  image: php:7.0-fpm
  volumes:
    - ../www/:/var/www/html